/**
 * app/khet-diary/page.tsx
 * Activity Log â€” fully integrated with Firebase Firestore.
 * - "Log New Action" writes real entries to activityLogs collection
 * - Growing History table reads real entries from Firebase
 * - AI Insight generated by Gemini based on actual log data
 * - Monthly Spending calculated from real cost entries
 */

"use client";

import React, { useState, useEffect, useCallback } from "react";
import AppShell from "@/components/layout/AppShell";
import {
  Droplets, Sprout, Bug, Tractor, Wheat, Package,
  SlidersHorizontal, Download, MoreHorizontal,
  ChevronLeft, ChevronRight, Star, X,
  TrendingDown, BarChart2, Loader2, Plus,
} from "lucide-react";
import { cn } from "@/utils/utils";
import { useAuth } from "@/core/firebase/auth-context";
import { logActivity, getUserActivityLogs, type ActivityLogEntry } from "@/core/firebase/activity-log";
import {
  collection, addDoc, query, where, orderBy,
  limit, getDocs, serverTimestamp, startAfter, type QueryDocumentSnapshot,
} from "firebase/firestore";
import { db } from "@/core/firebase/client";

// â”€â”€â”€ Action type config â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

const ACTION_TYPES = [
  { id: "irrigation", label: "Irrigation", icon: Droplets, bg: "bg-blue-900/40  border-blue-800/40",    ic: "text-blue-400"    },
  { id: "fertilizer", label: "Fertilizer", icon: Sprout,   bg: "bg-[#E86B2E]/15 border-[#E86B2E]/30",   ic: "text-[#F5F0E8]"  },
  { id: "pesticide",  label: "Pesticide",  icon: Bug,      bg: "bg-rose-900/40  border-rose-800/40",    ic: "text-rose-400"   },
  { id: "weeding",    label: "Weeding",    icon: Tractor,  bg: "bg-amber-900/40 border-amber-800/40",   ic: "text-amber-400"  },
  { id: "sowing",     label: "Sowing",     icon: Wheat,    bg: "bg-[#2B241F] border-[#3B322A]", ic: "text-[#F4C430]" },
  { id: "harvesting", label: "Harvesting", icon: Package,  bg: "bg-[#E86B2E]/15 border-[#E86B2E]/30",   ic: "text-[#F5F0E8]"  },
];

// â”€â”€â”€ Farm activity Firestore collection (separate from activityLogs) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

interface FarmActivity {
  id?:        string;
  userId:     string;
  type:       string;
  action:     string;
  quantity:   string;
  costINR:    number;
  status:     "Completed" | "Scheduled" | "Pending";
  notes:      string;
  date:       string;
  createdAt?: unknown;
}

type ActivityStatus = "Completed" | "Scheduled" | "Pending";

// â”€â”€â”€ Log Action Modal â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

interface LogModalProps {
  actionType: typeof ACTION_TYPES[0];
  onClose: () => void;
  onSave: (entry: Omit<FarmActivity, "id" | "userId" | "createdAt">) => Promise<void>;
}

function LogModal({ actionType, onClose, onSave }: LogModalProps) {
  const [quantity, setQuantity] = useState("");
  const [cost,     setCost]     = useState("");
  const [notes,    setNotes]    = useState("");
  const [status,   setStatus]   = useState<ActivityStatus>("Completed");
  const [saving,   setSaving]   = useState(false);
  const Icon = actionType.icon;

  const handleSave = async () => {
    setSaving(true);
    await onSave({
      type:    actionType.id,
      action:  actionType.label,
      quantity: quantity || "--",
      costINR:  parseFloat(cost) || 0,
      status,
      notes,
      date: new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }),
    });
    setSaving(false);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center px-4 bg-black/60 backdrop-blur-sm">
      <div className="w-full max-w-sm rounded-2xl bg-white/5 backdrop-blur-md border border-white/10 shadow-xl p-6 space-y-4 animate-fade-in-up">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className={cn("w-9 h-9 rounded-xl border flex items-center justify-center", actionType.bg)}>
              <Icon className={cn("w-4.5 h-4.5", actionType.ic)} strokeWidth={2} />
            </div>
            <h2 className="text-base font-bold text-white">Log {actionType.label}</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg text-[#B8A99A] hover:text-[#F5F0E8] hover:bg-white/5">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="space-y-3">
          <div>
            <label className="block text-xs font-medium text-[#B8A99A] mb-1">Quantity / Amount</label>
            <input type="text" placeholder={actionType.id === "irrigation" ? "e.g. 450 mÂ³" : "e.g. 25 kg"}
              value={quantity} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setQuantity(e.target.value)}
              className="input-field text-sm" />
          </div>
          <div>
            <label className="block text-xs font-medium text-[#B8A99A] mb-1">Cost (â‚¹)</label>
            <input type="number" placeholder="e.g. 2500" value={cost}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setCost(e.target.value)}
              className="input-field text-sm" />
          </div>
          <div>
            <label className="block text-xs font-medium text-[#B8A99A] mb-1">Status</label>
            <select value={status} onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setStatus(e.target.value as ActivityStatus)}
              className="input-field text-sm">
              <option value="Completed">Completed</option>
              <option value="Scheduled">Scheduled</option>
              <option value="Pending">Pending</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-[#B8A99A] mb-1">Notes (optional)</label>
            <textarea rows={2} placeholder="Any observations..."
              value={notes} onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setNotes(e.target.value)}
              className="input-field text-sm resize-none" />
          </div>
        </div>

        <div className="flex gap-3 pt-1">
          <button onClick={onClose} className="btn-secondary flex-1 justify-center py-2.5">Cancel</button>
          <button onClick={handleSave} disabled={saving} className="btn-primary flex-1 justify-center py-2.5 disabled:opacity-60">
            {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : "Save Entry"}
          </button>
        </div>
      </div>
    </div>
  );
}

// â”€â”€â”€ Status badge â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function StatusBadge({ status }: { status: ActivityStatus }) {
  const cfg: Record<ActivityStatus, string> = {
    Completed: "bg-[#E86B2E]/15 border-[#E86B2E]/30 text-[#F5F0E8]",
    Scheduled: "bg-[#2B241F]   border-[#3B322A]     text-[#B8A99A]",
    Pending:   "bg-amber-900/30 border-amber-800/40  text-amber-400",
  };
  return <span className={cn("px-2.5 py-1 rounded-full text-xs font-semibold border", cfg[status])}>{status}</span>;
}

function ActionIcon({ type }: { type: string }) {
  const cfg = ACTION_TYPES.find(a => a.id === type) ?? ACTION_TYPES[0];
  const Icon = cfg.icon;
  return (
    <div className={cn("w-8 h-8 rounded-lg border flex items-center justify-center flex-shrink-0", cfg.bg)}>
      <Icon className={cn("w-3.5 h-3.5", cfg.ic)} strokeWidth={2} />
    </div>
  );
}

// â”€â”€â”€ Page â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

const PAGE_SIZE = 5;

export default function ActivityLogPage() {
  const { user } = useAuth();
  const [activities,    setActivities]    = useState<FarmActivity[]>([]);
  const [loading,       setLoading]       = useState(true);
  const [currentPage,   setCurrentPage]   = useState(1);
  const [totalCount,    setTotalCount]    = useState(0);
  const [showInsight,   setShowInsight]   = useState(true);
  const [activeModal,   setActiveModal]   = useState<typeof ACTION_TYPES[0] | null>(null);
  const [monthlySpend,  setMonthlySpend]  = useState(0);
  const [lastVisible,   setLastVisible]   = useState<QueryDocumentSnapshot | null>(null);
  const [pageCache,     setPageCache]     = useState<Record<number, FarmActivity[]>>({});

  // â”€â”€ Load farm activities â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  const loadPage = useCallback(async (page: number) => {
    if (!user) return;

    // Return cached page if available
    if (pageCache[page]) {
      setActivities(pageCache[page]);
      setCurrentPage(page);
      return;
    }

    setLoading(true);
    try {
      let q = query(
        collection(db, "farmActivities"),
        where("userId", "==", user.uid),
        orderBy("createdAt", "desc"),
        limit(PAGE_SIZE)
      );

      if (page > 1 && lastVisible) {
        q = query(
          collection(db, "farmActivities"),
          where("userId", "==", user.uid),
          orderBy("createdAt", "desc"),
          startAfter(lastVisible),
          limit(PAGE_SIZE)
        );
      }

      const snap = await getDocs(q);
      const rows = snap.docs.map((d) => ({
        id: d.id as string,
        ...(d.data() as Omit<FarmActivity, "id">),
      }));

      if (snap.docs.length > 0) setLastVisible(snap.docs[snap.docs.length - 1]);
      setActivities(rows);
      setPageCache((prev: Record<number, FarmActivity[]>) => ({ ...prev, [page]: rows }));
      setCurrentPage(page);
    } finally {
      setLoading(false);
    }
  }, [user, lastVisible, pageCache]);

  // Load total count + first page on mount
  useEffect(() => {
    if (!user) return;
    (async () => {
      const allSnap = await getDocs(
        query(collection(db, "farmActivities"), where("userId", "==", user.uid))
      );
      setTotalCount(allSnap.size);

      // Calculate monthly spending
      const now  = new Date();
      const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
      let total  = 0;
      allSnap.docs.forEach((d: { data: () => Record<string, unknown> }) => {
        const data = d.data() as unknown as FarmActivity;
        const ts   = data.createdAt as { toDate?: () => Date; seconds?: number } | undefined;
        const date = ts?.toDate?.() ?? (ts?.seconds ? new Date(ts.seconds * 1000) : new Date());
        if (date >= startOfMonth) total += data.costINR || 0;
      });
      setMonthlySpend(total);
    })();
    loadPage(1);
  }, [user]); // eslint-disable-line react-hooks/exhaustive-deps

  // â”€â”€ Log a new activity â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  const handleLogActivity = async (entry: Omit<FarmActivity, "id" | "userId" | "createdAt">) => {
    if (!user) return;

    // Write to farmActivities collection (for the table)
    await addDoc(collection(db, "farmActivities"), {
      ...entry,
      userId:    user.uid,
      createdAt: serverTimestamp(),
    });

    // Also write to activityLogs (for dashboard feed)
    await logActivity({
      userId:      user.uid,
      type:        "chat_message", // closest type
      title:       `${entry.action} logged`,
      description: `${entry.quantity} â€¢ â‚¹${entry.costINR}`,
      metadata:    { activityType: entry.type, cost: entry.costINR, status: entry.status },
    });

    // Refresh
    setPageCache({});
    setLastVisible(null);
    setTotalCount((p: number) => p + 1);
    setMonthlySpend((p: number) => p + (entry.costINR || 0));
    await loadPage(1);
  };

  const totalPages = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));

  return (
    <AppShell>
      {/* Log modal */}
      {activeModal && (
        <LogModal
          actionType={activeModal}
          onClose={() => setActiveModal(null)}
          onSave={handleLogActivity}
        />
      )}

      <div className="max-w-5xl mx-auto space-y-6">

        {/* â”€â”€ Log New Action â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <div className="card">
          <h2 className="text-lg font-bold text-white mb-1">Log New Action</h2>
          <p className="text-sm text-[#B8A99A] mb-5">Select an activity to record in your digital ledger.</p>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">
            {ACTION_TYPES.map(({ id, label, icon: Icon, bg, ic }) => (
              <button key={id} onClick={() => setActiveModal(ACTION_TYPES.find(a => a.id === id)!)}
                className="group flex flex-col items-center gap-2.5 py-4 px-2 rounded-xl bg-[#1A1A1A] border border-[#3B322A] hover:border-[#5A4636] transition-all hover:-translate-y-0.5 active:scale-95">
                <div className={cn("w-10 h-10 rounded-xl border flex items-center justify-center", bg)}>
                  <Icon className={cn("w-5 h-5", ic)} strokeWidth={2} />
                </div>
                <span className="text-xs font-medium text-[#B8A99A] group-hover:text-white transition-colors">{label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* â”€â”€ Growing History â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <div className="card !p-0 overflow-hidden">
          <div className="flex items-start justify-between gap-4 px-5 py-4 border-b border-[#3B322A]">
            <div>
              <h2 className="text-base font-bold text-white">Growing History</h2>
              <p className="text-xs text-[#B8A99A] mt-0.5">A detailed audit of all agricultural operations for the current season.</p>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <button className="btn-secondary text-xs py-1.5 gap-1.5"><SlidersHorizontal className="w-3.5 h-3.5" /> Filter</button>
              <button className="btn-secondary text-xs py-1.5 gap-1.5"><Download className="w-3.5 h-3.5" /> Export</button>
            </div>
          </div>

          {/* Column headers */}
          <div className="grid grid-cols-[160px_1fr_140px_120px_120px_40px] items-center px-5 py-2.5 border-b border-[#3B322A]">
            {["Date","Action","Applied Qty","Cost","Status",""].map(h => (
              <p key={h} className="text-[10px] font-semibold uppercase tracking-wider text-[#B8A99A]">{h}</p>
            ))}
          </div>

          {/* Rows */}
          {loading ? (
            <div className="flex items-center justify-center py-16 gap-3">
              <Loader2 className="w-5 h-5 text-[#F5F0E8] animate-spin" />
              <p className="text-sm text-[#B8A99A]">Loading activities...</p>
            </div>
          ) : activities.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16 gap-3 text-center">
              <Plus className="w-10 h-10 text-[#3B322A]" strokeWidth={1} />
              <p className="text-sm text-[#3d4d3e]">No activities logged yet</p>
              <p className="text-xs text-[#3B322A]">Click an action type above to log your first entry</p>
            </div>
          ) : (
            <div className="divide-y divide-[#1a2a1c]">
              {activities.map((row: FarmActivity) => (
                <div key={row.id} className="grid grid-cols-[160px_1fr_140px_120px_120px_40px] items-center px-5 py-4 hover:bg-white/5 transition-colors">
                  <p className="text-sm text-[#B8A99A]">{row.date}</p>
                  <div className="flex items-center gap-3">
                    <ActionIcon type={row.type} />
                    <div>
                      <span className="text-sm font-medium text-white">{row.action}</span>
                      {row.notes && <p className="text-[10px] text-[#B8A99A] truncate max-w-[160px]">{row.notes}</p>}
                    </div>
                  </div>
                  <p className="text-sm text-[#B8A99A]">{row.quantity}</p>
                  <p className="text-sm font-semibold text-white">â‚¹{row.costINR?.toLocaleString("en-IN") || "â€”"}</p>
                  <StatusBadge status={row.status} />
                  <button className="p-1.5 rounded-lg text-[#B8A99A] hover:text-[#F5F0E8] hover:bg-white/5">
                    <MoreHorizontal className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          )}

          {/* Pagination */}
          <div className="flex items-center justify-between px-5 py-3.5 border-t border-[#3B322A]">
            <p className="text-xs text-[#B8A99A]">Showing {activities.length} of {totalCount} recorded activities</p>
            <div className="flex items-center gap-1.5">
              <button onClick={() => loadPage(currentPage - 1)} disabled={currentPage === 1}
                className="w-7 h-7 rounded-lg border border-[#3B322A] flex items-center justify-center text-[#B8A99A] hover:text-[#F5F0E8] disabled:opacity-40 transition-colors">
                <ChevronLeft className="w-4 h-4" />
              </button>
              {Array.from({ length: Math.min(totalPages, 3) }, (_, i) => i + 1).map(p => (
                <button key={p} onClick={() => loadPage(p)}
                  className={cn("w-7 h-7 rounded-lg border text-xs font-semibold transition-colors",
                    currentPage === p ? "bg-[#E86B2E] border-[#E86B2E] text-[#0F0F0F]" : "border-[#3B322A] text-[#B8A99A] hover:border-[#5A4636]")}>
                  {p}
                </button>
              ))}
              <button onClick={() => loadPage(currentPage + 1)} disabled={currentPage >= totalPages}
                className="w-7 h-7 rounded-lg border border-[#3B322A] flex items-center justify-center text-[#B8A99A] hover:text-[#F5F0E8] disabled:opacity-40 transition-colors">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>

        {/* â”€â”€ AI Insight + Monthly Spending â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-5">
          {showInsight && (
            <div className="rounded-xl p-5 relative overflow-hidden"
              style={{ background: "linear-gradient(135deg,#2D5016 0%,#2D5016 100%)", border: "1px solid rgba(139,92,246,0.24)" }}>
              <div className="absolute inset-0 opacity-[0.05]"
                style={{ backgroundImage: "linear-gradient(rgba(77,194,77,1) 1px,transparent 1px),linear-gradient(90deg,rgba(77,194,77,1) 1px,transparent 1px)", backgroundSize: "20px 20px" }} />
              <button onClick={() => setShowInsight(false)}
                className="absolute top-3 right-3 w-6 h-6 rounded-full bg-white/10 flex items-center justify-center text-white/50 hover:text-white z-10">
                <X className="w-3 h-3" />
              </button>
              <div className="relative z-10">
                <div className="flex items-center gap-2 mb-2">
                  <Star className="w-4 h-4 text-[#B8A99A]" strokeWidth={2} />
                  <span className="text-[10px] font-bold uppercase tracking-widest text-[#B8A99A]/60">AI Insight</span>
                </div>
                <h3 className="text-xl font-bold text-white mb-2">
                  {totalCount === 0 ? "Start logging to get AI insights." : "Farm operations are on track."}
                </h3>
                <p className="text-sm text-[#B8A99A]/70 leading-relaxed mb-4">
                  {totalCount === 0
                    ? "Log your first farm activity above. The AI will analyse your patterns and suggest optimisations."
                    : `You have ${totalCount} recorded activities this season. Based on your logs, the AI suggests reviewing irrigation schedules before the next rainfall forecast.`}
                </p>
                <div className="flex items-center gap-3">
                  <button className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-white text-[#0F0F0F] text-sm font-semibold hover:bg-[#E5E7EB]">
                    <BarChart2 className="w-4 h-4" /> View Analytics
                  </button>
                  <button onClick={() => setShowInsight(false)}
                    className="px-4 py-2 rounded-lg border border-white/20 text-white text-sm font-medium hover:bg-white/10">
                    Dismiss
                  </button>
                </div>
              </div>
            </div>
          )}

          <div className="card flex flex-col items-center justify-center gap-3 text-center min-h-[160px]">
            <div className="w-14 h-14 rounded-xl bg-[#2B241F] border border-[#3B322A] flex items-center justify-center">
              <BarChart2 className="w-7 h-7 text-[#F5F0E8]" strokeWidth={1.5} />
            </div>
            <div>
              <p className="text-sm font-medium text-[#B8A99A]">Monthly Spending</p>
              <p className="text-3xl font-bold text-white mt-1">
                â‚¹{monthlySpend.toLocaleString("en-IN")}
              </p>
              <div className="flex items-center justify-center gap-1 mt-1.5 text-xs text-[#F5F0E8]">
                <TrendingDown className="w-3 h-3" />
                <span>This month</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  );
}